server:
  port: 8101

api:
  stockprice5min:
    domain: 'bc-yahoo-finance:8100'
    endstocklist: /stocklist
    endpoint5min: /stock5minquote
    endpointHistory: /history

spring:
  application:
    name: bc-stock-web